### PR TITLE
Release/ipm 2.2.0

### PR DESCRIPTION
**Pull request by perrettecl**
Backport from recent release hotfixes into main development trunk.

### CODE REVIEW

**Review by aquette — APPROVED** [review]
seems good to me,  but reviewed too fast!

**Comment by jimklimov** [comment]
Upon closer inspection, by the list of commits and now going over contents, this backport seems not needed in the end since the original fixes were dual-PR-ed into main (FTY) and release branches independently already - same situation as in #123 before it.

Doing a `git diff branch1..branch2` in a local workspace before posting should really help weed out such noise: apparently GitHub compares commits as a whole (and frankly, so does the `git` 3-way-diff in `git mergetool`), so applying all the changes to target branch since it split ways with the release branch on one hand, and all the changes in the target branch since that point in another, disregarding if the changes were identical in content and leaving to the humans to discover that and decide. They may have different metadata and commit hashes though, e.g. due to different merge-commits in the histories, so usually pedantically *are* different - but that is not of much practical use to us except to have a recent common-state point in the two branches at expense of noise in the history of main trunk. Since we dual-post most of the fixes initially, we can forgo polluting the main history.

Dupe sets here:

* snmp-ups: Restore legacy Eaton ePDU switchability info #118
* snmp-ups: Restore legacy Eaton ePDU switchability info (2.2.0) #119

* snmp-ups: fix instant commands using numeric parameters #120
* [2.2.0] snmp-ups: fix instant commands using numeric parameters #121

* snmp-ups: fix regression on Eaton ePDU #125
* snmp-ups: fix regression on Eaton ePDU (2.2.0) #124

I think this covers all the changes in the backport.

**Comment by jimklimov** [comment]
So, after making an experiment with a new local branch off of FTY, and merging release on top of it (with a few conflicts to solve due to fixed lookup table names and explicit NULL fields for `ifdef DMF` in the main development branch), and rebasing again over FTY to filter out just the content changes brought from release... in the end there were none.

**Comment by jimklimov** [comment]
So, thanks for highlighting that there were differences - but in the end, none to backport into FTY branch. Closing the PR.

**Pull request closed without merging**
