### PR TITLE
NUT master improvements backported into DMF-aware FTY branch

### PR DESCRIPTION
**Pull request by jimklimov**

### CODE REVIEW

**Comment by jimklimov** [comment]
So, there is good news and bad news: good news is that changes of "original" NUT upstream are now in this fork too, and with recently added commits it no longer crashes in the selftest; bad news would be that it seems some of those changes applied to DMF codebase broke reading of data from DMF files. The test program sees a list of MIB mappings for different devices, but apparently ends up with empty tables for OID mappings of each single such device type.

Currently `dmf-test` detects this situation (that the first entry in the table is already a sentry with NULL fields) and deliberately returns exit-code 2 in the end; if we tweak that source a little to ignore the failure to have green merges, we would end up with 42ITy NUT that incorporates improvements from upstream as well as its own not yet upstreamed goodness, but lacks DMF until fixed.

Upon discussion with our Release Engineer, we decided to go this way - merge what we have and what works at the moment, so other team members can test and experience these changes, and separately work on fixing the bug in another PR. For porting into 1.5.0 both of these PRs (this one and new one) would be needed.

The legacy SNMP driver, as well as other parts of this software, is expected to work properly. Note that our "devel" images use the `snmp-ups-dmf` driver by default and may be impacted by this choice; the "deploy" images use the legacy driver by default and should not notice this.

**Comment by jimklimov** [comment]
I extracted the commits which fixed buildability and testability for me as I developed this backport into #76 and in particular checked that DMF-aware part codebase before these backports passed its tests well, in otherwise same environment. So something here in the difference of `backport-201902` and `FTY-fixbuild` branches is the culprit...

**Comment by jimklimov** [comment]
One remaining red flag in tests is a warning about unused variables. It was not present before the backports so may be the culprit, so I am reluctant to handwave it away with preprocessor macros etc. without investigation (though it may make sense to merge for Release Engineering reasons commented above).

@jana-rapava : would you have time to look into this branch today? Maybe I had some typo or commented away a bit too much? If not, I hope to get back to this tonight.

**Comment by jana-rapava** [comment]
@jimklimov : I can be looking at it until something more critical shows up :-)

**Comment by jimklimov** [comment]
Great job, I verified that `dmf-test` in Travis logs does load the DMF, no skipping. So the commit about not-returning an error in `dmf-test` if tables are empty can be reverted, but it can happen later as another PR.

Now hope our CI systems confirm the PR and we can merge it to FTY and initiate an equivalent set of commits for 1.5.0.

**Pull request merged**
