### PR TITLE
Update emp002

### PR DESCRIPTION
**Pull request by eric3873**
Add EMP002 modbus address and epdu uuid/id in NUT

### CODE REVIEW

**Review by boricj — APPROVED** [review]

**Comment by boricj** [comment]
@perrettecl Travis CI is enabled here, we need to remove it.

**Comment by jimklimov** [comment]
We still sync between upstream and 42ity forks, for components were we have Travis in upstream we do not remove it.

**Comment by jimklimov** [comment]
As for this PR, the DMF file was not changed in Git, and the CI build says just that :)

**Comment by jimklimov** [comment]
Barring typos, should be OK now. I disabled Travis builds in account settings, so should only wait for Jenkins CI now.

**Review by jimklimov — APPROVED** [review]
Tentatively approving - LGTM if CI says the result is green :)

**Review by aquette — CHANGES_REQUESTED** [review]
Docs/nut-names.txt should be updated too

**Comment by aquette** [comment]
@jimklimov FYI, I asked Eric to change these names to more generic ones, as per the main principles on how I setup this naming scheme.
Pay attention to new variables not added in it ;)

**Review by aquette — APPROVED** [review]

**Comment by jimklimov** [comment]
I do not quite see how e08d9047446b2c1ccb724c36431bbc6df8cf91a8 is related to dropping a bit of code from snmp-ups? Is that a typo or intentional change?

**Comment by eric3873** [comment]
No it is an intentional change for oid read value issue. But thanks I fix the identation issue.

**Comment by aquette** [comment]
Checked with me @jimklimov

**Pull request merged**
