### PR TITLE
Pqswmbt 4637 fix dry contacts status (FTY main branch)

### PR DESCRIPTION
**Pull request by eric3873**
fix dry contacts status  for emp02

### CODE REVIEW

**Review by perrettecl — APPROVED** [review]

**Review by jimklimov — APPROVED** [review]
I remember that did look fishy to me at some point; I suppose the correct status mapping is now experimentally confirmed? ;)

**Comment by eric3873** [comment]
Yes I have confirmed with my sample but need to be confirmed by qualification team (in progress)

**Review by aquette — APPROVED** [review]

**Comment by jimklimov** [comment]
As highlighted for #127, this change warrants a driver-version bump.

**Comment by jimklimov** [comment]
Confirmed on call today that we should still wait for a verdict from validation against HW.

**Pull request merged**
